### ISSUE TITLE
Request for update

### ISSUE THREAD

**Issue by dhruvdg5** [lolapus/Bitcoin-private-key-generator#2]
Please add multiprocessing  and ability  to run and utilize gpu.
Also add the percentage  limit like 80 70% etc.
Thank you.

**Comment by blackunixteam** [comment]
https://github.com/blackunixteam/btc-privkey-search <-percentage

**Comment by lolapus** [comment]
@dhruvdg5 Sorry but no more updates as I made this as an experiment and not to actually be used.
